version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
after_build:
- '7z a flick-uploader-cli.zip %APPVEYOR_BUILD_FOLDER%\src\FlickrUploader.Console\bin\publishOutput\*.*'
test: off  
artifacts:  
- path: flick-uploader-cli.zip
  name: flickr-uploader-cli
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tgBOf2r+5PXSYpvfB+041SWxfv0fWwpbq1gWffX3vg3xLawzHiUMjt5qEQQ6nBF1
  artifact: flickr-uploader-cli
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only