version: '1.0.{build}'
pull_requests:  
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
after_build:
- '7z a flick-uploader-cli-win-x86.zip %APPVEYOR_BUILD_FOLDER%\src\FlickrUploader.Console\bin\publishOutput\win-x86\*.*'
- '7z a flick-uploader-cli-linux-x64.zip %APPVEYOR_BUILD_FOLDER%\src\FlickrUploader.Console\bin\publishOutput\linux-x64\*.*'
test: off  
artifacts:  
- path: 'flick-uploader-cli*.zip'
  name: flickr-uploader-cli
deploy:
  release: flickr-uploader-cli-v$(appveyor_build_version)
  description: 'Flickr uploader CLI'
  provider: GitHub
  auth_token:
    secure: tgBOf2r+5PXSYpvfB+041SWxfv0fWwpbq1gWffX3vg3xLawzHiUMjt5qEQQ6nBF1
  artifact: flickr-uploader-cli
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
